accounts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^signup/$', views.signup),
]

askdjango/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^$' , lambda r: redirect('blog:index')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<post_pk>\d+)/comments/new/$', views.comment_new, name='comment_new'),
]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    photo = models.ImageField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.pk])


class Comment(models.Model):
    post = models.ForeignKey(Post)
    author = models.CharField(max_length=20)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm


class SignupForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        # fields = ['username']
        fields = ['username', 'email']

blog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['message']

accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.views import login
from .forms import SignupForm


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect('/')
    else:
        form = SignupForm()

    return render(request, 'accounts/signup_form.html', {
        'form': form,
    })

blog/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .models import Post
from .forms import CommentForm


def index(request):
    post_list = Post.objects.all()
    return render(request, 'blog/post_list.html', {'post_list': post_list})


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})


def comment_new(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)

    if request.method == 'POST':
        form = CommentForm(request.POST, request.FILES)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect(post)
    else:
        form = CommentForm()

    return render(request, 'blog/comment_form.html', {
        'post': post,
        'form': form,
    })

accounts/templates/accounts/signup_form.html
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" />
</form>

blog/templates/blog/base.html
{% load staticfiles %}<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>Ask Django's Blog</title>
<link rel="stylesheet" href="{% static "bootstrap/3.3.6/css/bootstrap.min.css" %}" />
<style>
body {
    padding-top: 60px;
}
html {
  position: relative;
  min-height: 100%;
}
body {
  margin-bottom: 60px;
}
.footer {
  position: absolute;
  bottom: 0;
  width: 100%;
  height: 60px;
  background-color: #f5f5f5;
}
</style>
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url "blog:index" %}">Ask Django's Blog</a>
        </div>
    </div>
</div>

{% block content %}
{% endblock %}

<div class="footer">
    <div class="container">
        <p class="text-muted">&copy; AskDjango</p>
    </div>
</div>

</body>
</html>

blog/templates/blog/comment_form.html
{% extends "blog/base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-offset-3 col-sm-6">
            <div class="panel panel-info">
                <div class="panel-heading">
                    &lt;{{ post.title }}&gt; 댓글쓰기
                </div>
                <div class="panel-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        <input type="submit" class="btn btn-primary" />
                    </form>
                </div>
                <div class="panel-footer">
                    <a href="{% url "blog:post_detail" post.pk %}" class="btn btn-default">돌아가기</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-info">
                <div class="panel-heading">
                    {{ post.title }}
                </div>
                <div class="panel-body">
                    <img src="{{ post.photo.url }}" style="max-width: 100%;" />
                    {{ post.content|linebreaks }}
                    <hr/>
                    
                    <ul>
                    {% for comment in post.comment_set.all %}
                        <li>{{ comment.message }}</li>
                    {% empty %}
                        <li><a href="{% url "blog:comment_new" post.pk %}">댓글을 써주세요.</a></li>
                    {% endfor %}
                    </ul>
                </div>
                <div class="panel-footer">
                    <a href="{% url "blog:index" %}" class="btn btn-default">글목록</a>
                    <a href="{% url "blog:comment_new" post.pk %}" class="btn btn-primary">댓글쓰기</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/base.html" %}

{% block content %}
<div class="container">
    <div class="row">
        {% for post in post_list %}
            <div class="col-sm-3">
                <div class="thumbnail">
                    <img src="{{ post.photo.url }}" />
                    <h4>
                        <a href="{% url "blog:post_detail" post.pk %}">
                            {{ post }}
                        </a>
                    </h4>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}